# Generated by Django 2.1.1 on 2018-09-18 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('post', models.CharField(max_length=20)),
                ('dob', models.DateTimeField(max_length=20)),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(max_length=10)),
            ],
        ),
    ]
